services:
    php:
        image: ghcr.io/sylius/sylius-php:8.2-fixuid-xdebug-alpine
        user: ${DOCKER_USER:-1000:1000}
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
            # Then PHPStorm will use the corresponding path mappings
            PHP_IDE_CONFIG: serverName=sylius
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/srv/sylius:rw,cached
            # if you develop on Linux, you may use a bind-mounted host directory instead
            #          - ./var:/srv/sylius/var:rw
            - ./public:/srv/sylius/public:rw,delegated
            # if you develop on Linux, you may use a bind-mounted host directory instead
            #          - ./public/media:/srv/sylius/public/media:rw
            - public-media:/srv/sylius/public/media:rw
    mysql:
        volumes:
            - mysql-data:/var/lib/mysql:rw
        ports:
            - "3306:3306"
    nginx:
        volumes:
            - ./public:/srv/sylius/public:ro
            # if you develop on Linux, you may use a bind-mounted host directory instead
            #            - ./public/media:/srv/sylius/public/media:ro
            - public-media:/srv/sylius/public/media:ro,nocopy
        ports:
            - "80:80"
    nodejs:
        image: node:${NODE_VERSION:-18}-alpine
        user: ${DOCKER_USER:-1000:1000}
        working_dir: /srv/sylius
        entrypoint: ["/bin/sh", "-c"]
        command:
            - |
                npm install
                npm run build
        volumes:
            - .:/srv/sylius:rw,cached
            - ./public:/srv/sylius/public:rw,delegated
    mailhog:
        ports:
            - "8025:8025"

volumes:
    mysql-data:
    public-media:
